services:
  postgres:
    image: postgres:16-alpine
    container_name: budget-db
    environment:
      POSTGRES_DB: budget_db
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: budget1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
